# Generated by Django 4.0.4 on 2022-05-02 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employee_options_alter_position_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='boss',
            new_name='parent',
        ),
    ]
