# Generated by Django 4.0.4 on 2022-05-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_rename_boss_employee_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='slug',
            field=models.SlugField(default=1, max_length=128, unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
