# Generated by Django 4.0.4 on 2022-05-04 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employee_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_photo',
            field=models.ImageField(blank=True, default='photo/default.png', upload_to='', verbose_name='Фото работника'),
        ),
    ]
