# Generated by Django 4.0.4 on 2022-05-06 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_alter_employee_employee_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Работник', 'verbose_name_plural': 'Работники'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_photo',
            field=models.ImageField(default='photo/default.png', upload_to='photo/', verbose_name='Фото работника'),
        ),
    ]
